### ISSUE TITLE
Not works for ts 1196

### ISSUE THREAD

**Issue by hexh250786313** [yoavbls/pretty-ts-errors#121]
ts 1196: `Catch clause variable type annotation must be 'any' or 'unknown' if specified.`

ref: https://typescript.tv/errors/#ts1196

![image](https://github.com/user-attachments/assets/37016411-bc90-492e-b79c-d7608ab2f619)

I have tried to debug and it just throws a error:

![image](https://github.com/user-attachments/assets/7132f4da-bb0e-49d7-8bd3-7308e2da2d7e)

It seems the following function receives a `22` as param causing the error.

https://github.com/yoavbls/pretty-ts-errors/blob/18647c1a58fbbef86e3bdbeecfccac11bbe5c9c8/src/format/formatTypeBlock.ts#L8-L16

**Comment by kevinramharak** [comment]
Hi @hexh250786313,

Thank you for reporting this error, it is indeed a regex issue. Probably because the existing pattern matches don't account for the syntax of this case.

Stacktrace:
```
stack trace: TypeError: type.match is not a function
extensionHostProcess.js:205
    at formatTypeBlock (d:\Projects\open-source\pretty-ts-errors\src\format\formatTypeBlock.ts:16:12)
extensionHostProcess.js:205
    at d:\Projects\open-source\pretty-ts-errors\src\format\formatDiagnosticMessage.ts:48:50
```

The issue happens at https://github.com/yoavbls/pretty-ts-errors/blob/e041cfd4ffb6ad8d252e554a10a0ed757e8b1992/src/format/formatDiagnosticMessage.ts#L48-L52
The second call to `formatTypeBlock` is where the error occurs. `formatTypeBlock` expects `p3` here to be a string containing a valid TypeScript type; instead, it is the number `22`.

Looking at the docs of a [replacer function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_function_as_the_replacement) it seems to match the `offset` argument.

I will create a PR to detect the case, as that will at least fix the issue for now. I'm hoping the regexes can be cleaned up in a more thorough change at a later date.
