### ISSUE TITLE
UNRESPONSIVE extension host with Drizzle, Kysely and a Big Schema

### ISSUE THREAD

**Issue by smhmayboudi** [yoavbls/pretty-ts-errors#122]
**Describe the bug**

I am using Drizzle and Kysely together. I have a database schema with nearly 200 tables. I do not define any relation between Drizzle and Kysely. I have select a query with more than 5 inner join tables. When I make some changes to my select, the vs code stops working properly. The windows out put is here.

```
2024-09-11 14:05:10.822 [info] UNRESPONSIVE extension host: starting to profile NOW
2024-09-11 14:05:15.888 [warning] UNRESPONSIVE extension host: 'yoavbls.pretty-ts-errors' took 100% of 5003.334ms, saved PROFILE here: 'file:///var/folders/7x/rxw2srxn4jzfp15n_f8th2gh0000gn/T/exthost-acaf0e.cpuprofile'
2024-09-11 14:05:48.905 [error] Error: Aborted onWillSaveTextDocument-event after 1750ms
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1873:13070
2024-09-11 14:05:53.950 [error] Error: Aborted onWillSaveTextDocument-event after 1750ms
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1873:13070
2024-09-11 14:06:21.965 [info] Extension host (LocalProcess pid: 38659) is responsive.
```

**Expected behavior**

Works fine.

**Original error**
If this bug is related to an error that is not formatting well, please
attach the original error in a code block:
<code>
Type 'number' is not assignable to type 'string'.ts(2322)
</code>

**Screenshots**

![IMAGE](https://github.com/user-attachments/assets/7329bb2e-b47e-4f3c-9caa-b43e84032d98)

**Comment by kevinramharak** [comment]
Thanks for the report. Do you still happen to have the original cpuprofile file? If so please attach it.
The window output & the screenshot might help a lot, because I'm still not sure why the onDiagnostics task is being run in that context. But it seems this is the first issue where the stack trace is similar to another performance issue.
